# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Ytterbium
  ru: Иттербий
email: info@ytterbium.space
description:
  en: A new generation of on-board frequency standards
  ru: Новое поколение бортовых стандартов частоты
keywords:
  en: "optical frequency standard, optical clock, Navigation Satellite System, ultracold ions, high finesse optical cavity, femtosecond frequency comb, ytterbium optical clock, quadrupole ion trap, GNSS, unmanned systems"
  ru: "оптические стандарты частоты, оптические часы, спутниковые навигационные системы,ультахолодные ионы, высокостабильные оптические резонаторы, фемтосекундный синтезатор частоты, иттербиевый стандарт частоты, квадрупольная ионная ловушка, ГЛОНАСС, беспилотные системы"
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "http://www.ytterbium.space" # the base hostname & protocol for your site
# github_username:  5981

# theme: jekyll-theme-cayman

# Build settings
# markdown: kramdown
